[platformio]
src_dir = firmware/solar_main

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
